// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofcvupapcgbleqxpinsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mY3Z1cGFwY2dibGVxeHBpbnNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNzIwMzAsImV4cCI6MjA2Njc0ODAzMH0.bgYq7w2PG7jNXGTCeX4LlG9hPKax4qDDom9WM6s3n2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);